### ISSUE TITLE
Stopping live capture on a condition

### ISSUE THREAD

**Issue by chadianscot** [KimiNewt/pyshark#129]
Is there any way I could use the sniff_continuously function to sniff an interface until a condition is met, at which point the capture is stopped?

**Comment by KimiNewt** [comment]
If you're running a loop, you can simply add a condition and then break out of the loop when that condition is satisfied -- that'll stop the capture.

I can also add a StopCapture exception to the apply_on_packets function to make the exit smoother if you're using a callback instead of a loop.

Reopen if neither solve it.
