### ISSUE TITLE
_cleanup_subprocess in capture.py is not terminating properly leaving a zombie process

### ISSUE THREAD

**Issue by rk0038397** [KimiNewt/pyshark#168]
Hello,

Please follow below steps to reproduce the issue:

File: test.pcap

open python console on Linux machine:

>> import pyshark

>> cap = pyshark.FileCapture("test.pcap")

>> cap[0] # This will start the tshark process

>> import os

>> pid=os.getpid() # Get the PID of the parent process

>> cap.running_processes # Gives child processes running as a result of cap[0]

>> cap.close()

Please don't exit from the python console.

say: pid = 1234

When you run 'ps aux' | grep 'Z' , you can see that tshark process is exited and left as zombie process.

Also the file descriptors opened by tshark process are not closed. You can check this with below command:

ls -l /proc/1234/fd    (pid = 1234)

**Comment by kondonky** [comment]
I had the same problem while I run my code.
Changing PyShark version and Python version, I have checked the problem using macOS Sierra.
The source code I used opened pcap file (`cap = pyshark.FileCapture("one of the files")`), extracted information, and closed the file (`cap.close()`), and this procedure was repeated to analyse some pcap files.
Here is the result and the main problem is that `cap.close()` does not work well (as a result, zombie processes are left).

v0.3.7.2: Python 3.6 (zombie process) / Python 2.7.13 (zombie process)
v0.3.6.2: Python 3.6 (zombie process) / Python 2.7.13 (zombie process)
v0.3.6: Python 3.6 (failed because of another reason) / Python 2.7.13 (zombie process)
v0.3.4: Python 3.6 (failed because of another reason) / Python 2.7.13 (zombie process)
v0.3: Python 3.6 (failed because of another reason) / Python 2.7.13 (failed because of another reason)

This problem seemed to be happened in PyShark v0.3.X, so that I tried to use PyShark v0.2.5 and in this version `cap.close()` worked well.
Zombie process should be serious problem when people want to analyse data using many pcap files.

**Comment by mfallone** [comment]
I am having the same issue.  I have been getting around it by closing the eventloop:

```
if not cap.eventloop.is_closed():
    cap.eventloop.close()
```

**Comment by rtoijala** [comment]
Hello, is there any progress on this?
@mfallone where exactly did you close the eventloop? Placing your code snippet above or below the capture.close() call does not work for me.

**Comment by KimiNewt** [comment]
Should be fixed now, reopen if there any issues.

**Comment by wordhardqi** [comment]
The problem still exists in the newest version on Mac.

**Comment by KimiNewt** [comment]
Hi @wordhardqi , are you explicitly calling cap.close() or waiting for garbage collection?

**Comment by sikam** [comment]
Same problem here:

capture1 = pyshark.FileCapture(file1_path_name, tshark_path=PathToTshark)
print(capture1[0])
capture1.close()

capture2 = pyshark.FileCapture(file2_path_name, tshark_path=PathToTshark)
print(capture2[0])
capture2.close()
Encountered this issue with pyshark 0.3.7.9 on Python 3.6.2 on Win7 64bit
Are there any plans on fixing this issue?
