### ISSUE TITLE
DNS Answers

### ISSUE THREAD

**Issue by jhanna01** [KimiNewt/pyshark#216]
There doesn't appear to be a way to get all the IP answers sent in a DNS response. 
While ```dns.count.answers``` gives the correct number of answers, ```dns.a``` will only return the first answer IP, rather than a list of all the answer IPs given.

**Comment by jhanna01** [comment]
Figured out how to do this. dns.a.all_fields will give you all answers in a list.

**Comment by DD152** [comment]
Excuse me,i have similar problem.How did you know add  `all_fields` after `dns.a`?
I didn't find `all_fields` in [wireshark wiki](https://www.wireshark.org/docs/dfref/d/dns.html).
Forgive my stupidity.
Thanks.

**Comment by DD152** [comment]
> Excuse me,i have similar problem.How did you know add `all_fields` after `dns.a`?
> I didn't find `all_fields` in [wireshark wiki](https://www.wireshark.org/docs/dfref/d/dns.html).
> Forgive my stupidity.
> Thanks.

[solution](https://github.com/KimiNewt/pyshark/issues/469)

**Comment by jiamo** [comment]
I found:
`len(dns.a.all_fields) =  dns.count_answer + dns.count_auth_rr`

Is there document for this?

**Comment by jvmk** [comment]
> I found: `len(dns.a.all_fields) = dns.count_answer + dns.count_auth_rr`
> 
> Is there document for this?

I'm curious about this as well. In a DNS response packet, how do we map a domain to an IP, when the response contains additional RRs and/or NS records? For example, since `dns.resp_name.all_fields` will list all domains (across different record types, additional RRs, NS etc.), how do we map an entry in e.g. `dns.a.all_fields`, `dns.aaaa.all_fields` etc. to a domain in `dns.resp_name.all_fields`?
