### ISSUE TITLE
RuntimeError: Program failed to run. Retcode: 127. Cmd: ['/usr/local/bin/tshark', '-v'] 

### ISSUE THREAD

**Issue by hmchaitra** [KimiNewt/pyshark#229]
Whats the error i am unable to understand can any one help me out??
is this because wireshark path is different

**Comment by JuhPuur** [comment]
Retcode 127 indicates the executable was not found in that path.
'<path>/tshark -v' is called in tshark.py:get_tshark_version(), and get_process_path() should catch nonexistent paths before attempting to execute.
Assuming you're running linux, try running "which tshark" in the console. It should output the location of the tshark binary(if installed, otherwise nothing). Then try running it manually.

**Comment by hmchaitra** [comment]
thank you, i uninstalled the wireshrk and installed properly,earlier some shared libraries were not set properly in the path so wireshark was running only in particular path , now it works fine.

**Comment by JuhPuur** [comment]
This can probably be closed then.
