### ISSUE TITLE
Cannot extract wlan.fc_retry field from LiveCapture with arg use_json=True

### ISSUE THREAD

**Issue by anotherfiz** [KimiNewt/pyshark#235]
When doing a live capture with the following argument: 

`self.capture = pyshark.LiveCapture(interface="mon0",use_json=True, bpf_filter=bpf_filter)`

I get the following error:
Traceback (most recent call last):
  File "./Test.py", line 253, in process_packet
    retry = packet.wlan.fc_retry
  File "/usr/lib/python2.7/site-packages/pyshark/packet/layer.py", line 34, in __getattr__
    val = self.get_field(item)
  File "/usr/lib/python2.7/site-packages/pyshark/packet/layer.py", line 236, in get_field
    raise AttributeError("No such field %s" % name)
AttributeError: No such field fc_retry
No such field fc_retry

I have tested this on two Ubuntu 16.04 systems as well as Intel Joule embedded system running Yocto@4.9 kernel.  removing the use_Json = true argument allows access of the field.  

Thank you.

**Comment by ZackAlfakir** [comment]
bump, same issue here.

**Comment by KimiNewt** [comment]
Accessing fields works slightly differently when using JSON, because of the way the tshark JSON is organized. Fields will be accessed with "." instead of "_" like in wireshark itself (you can see the field name in the bottom left).

Also, you can access a field's value by accessing its name and access its subfields by accessing "<field_name>_tree". That's just the way the JSON is structured.

You can access the field you want by using `packet.wlan.fc_tree.flags_tree.retry`. Or the whole flags field by using `w.wlan.fc_tree.flags`. I recommend using an interpreter to find the attributes you need or just printing the packet to see how to access it.
