### ISSUE TITLE
Too many files opened

### ISSUE THREAD

**Issue by giovanig** [KimiNewt/pyshark#238]
Hi,
I have a simple UDP sniffer script:

while True:
    capture = pyshark.LiveCapture(interface=INTERFACE, bpf_filter="udp")
    pkt_list = []    
    capture.apply_on_packets(get_timestamp, packet_count=BUFFERSIZE)
    capture.close()

The problem is that the script is being killed by the OS (Linux), because it is reaching the limit of opened files. The pyshark version is 0.3.7.11. Any solution?

**Comment by vnyb** [comment]
I'm encountering a problem that seems to be related. The subprocesses launched by pyshark are not cleaned properly. They stay in the zombie state because the parent process does not wait for the exit status.

It is possible to observe this with this simple script below:
```
import time
import pyshark

capture = pyshark.LiveCapture(interface='br0')
capture.sniff(timeout=5)
capture.close()
del capture

while True:
    time.sleep(5)
```

After five seconds, the subprocesses are supposed to be stopped but they are marked as defunct:
```
ps aux | grep -E "(tshark|dumpcap)"
root     23526  0.1  0.0      0     0 pts/6    Z+   09:18   0:00 [dumpcap] <defunct>
root     23527  1.2  0.0      0     0 pts/6    Z+   09:18   0:00 [tshark] <defunct>
```

In your case, multiple processes are launched by the loop until the file descriptor limit is reached.
