### ISSUE TITLE
Cannot access multiple WLAN layers

### ISSUE THREAD

**Issue by geansriffin** [KimiNewt/pyshark#266]
I am looking at a saved packet capture collected from my Macbook Air with Wireshark.  I am using python 3.6.1.  When looking at beacon/probe requests I am seeing multiple layers with a `wlan` name:

```
packet
Out[21]: <WLAN Packet>
packet.layers
Out[22]: [<RADIOTAP Layer>, <WLAN_RADIO Layer>, <WLAN Layer>, <WLAN Layer>]
```

Unfortunately, I have no way of accessing the second WLAN layer as `packet.wlan` only refers to the first layer.  I also have no reliable way of retrieving the second WLAN layer without probing each layer with `if`/`then` statements when processing.

Am I missing something obvious?

**Comment by sin3t** [comment]
Hi geansriffin,
I have faced with the same problem, and it seems, that tshark passes these fields with non uniq keys (wlan), that is why they are accessible only in non-attribute manner (due to python limitations) and it's not a pyshark issue.

So, you can extract them via:

- direct indexing with additional availability checks 
(`packet.layer[2]`, `packet.layer[3]` - the ugly way);
- list unpacking with additional availability checks 
(`radiotap, wlan_radio, wlan_gen, wlan_data = packet.layers`);
- native pyshark workaround - packet.get_multiple_layers('wlan'):

src/pyshark/packet/packet.py
`def get_multiple_layers(self, layer_name):`

> Returns a list of all the layers in the packet that are of the layer type (an incase-sensitive string).
> This is in order to retrieve layers which appear multiple times in the same packet (i.e. double VLAN) which cannot be retrieved by easier means.
>
