### ISSUE TITLE
PyShark Documenation

### ISSUE THREAD

**Issue by ozn17** [KimiNewt/pyshark#276]
Where is the documentation for this package?  Normally there is a pypi/pydocs documenation page for most python packages.  Other than the github readme, there is no proper documentation other than random folks on internet that barely touch the package.

Am I missing something?

**Comment by KimiNewt** [comment]
There's (very) slightly more documentation at: http://kiminewt.github.io/pyshark

You're not missing anything, I just didn't have the time to write docs (nor did anyone else). I want to do so but I can't promise anything. I might add a video tutorial at some point because it will be less time-consuming for me (but more for whoever needs it).

**Comment by AMNeves** [comment]
I was also going to write an issue about the documentation, i am currently doing a monitor mode sniffer and have to dissect packets, and it is horrible having to parse everything by myself everytime i need to do something to see what options i have, Is there anyway i can see packets structure not at runtime?
