### ISSUE TITLE
 How can sniff the packet and print the packet immediately?

### ISSUE THREAD

**Issue by al-ani** [KimiNewt/pyshark#278]
I am trying to used Pyshark to sniff packets and print them.
but I find I can only sniff a certain amount of packets and then I can print them.
So how can I print every single packet that sniffed immediately?

**Comment by ZackAlfakir** [comment]
libpcap will buffer some packets and then deliver them all at once. In order to do absolute real-time, you will have to enable an option in libpcap. Note that it will result in a performance hit, so if you are sniffing a lot of packets, you may end up dropping more of them then you would with buffered libpcap.

I believe pyshark also has a small buffer for the same reason. 

If you really need to have the packet instantly, I suggest using scapy SuperSockets. However, you should question if you really need that packet to show up immediately, as it is not a sustainable model.
