### ISSUE TITLE
Tshark crashes when using LiveRingCapture

### ISSUE THREAD

**Issue by 0x4D31** [KimiNewt/pyshark#299]
I get the following error when I try to use LiveRingCapture:

\>>> capture = pyshark.LiveRingCapture(interface='en1')
\>>> capture.set_debug()
\>>> for packet in capture.sniff_continuously(packet_count=0):
...     print('Just arrived')

>[2018-09-25 07:03:20.589468] DEBUG: LiveRingCapture: Creating Dumpcap subprocess with parameters: /usr/local/bin/dumpcap -q -P -i en1 -w -
[2018-09-25 07:03:20.593250] DEBUG: LiveRingCapture: %s subprocess created
[2018-09-25 07:03:20.593973] DEBUG: LiveRingCapture: Creating TShark subprocess with parameters: /usr/local/bin/tshark -l -n -T pdml -r - -b filesize:1024 -b files:1 -w /tmp/pyshark.pcap -P
[2018-09-25 07:03:20.596847] DEBUG: LiveRingCapture: %s subprocess created
Capturing on 'Ethernet 2'
File: -
tshark: Multiple capture files requested, but a capture isn't being done.
[2018-09-25 07:03:20.923635] DEBUG: LiveRingCapture: EOF reached (sync)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pyshark/capture/capture.py", line 229, in _packets_from_tshark_sync
    self.eventloop.run_until_complete(self._cleanup_subprocess(tshark_process))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/pyshark/capture/capture.py", line 399, in _cleanup_subprocess
    % process.returncode)
pyshark.capture.capture.TSharkCrashException: TShark seems to have crashed (retcode: 1). Try rerunning in debug mode [ capture_obj.set_debug() ] or try updating tshark.

As you can see it creates Tshark subprocess using the following parameters:
`tshark -l -n -T pdml -r - -b filesize:1024 -b files:1 -w /tmp/pyshark.pcap -P`
If you run Tshark with these parameters you get the following error:
`tshark: Multiple capture files requested, but a capture isn't being done.`
Which is because of `-r -` option (if you remove -r, it works) that is added in the following commit (changed -i to -r):
https://github.com/KimiNewt/pyshark/commit/0855e73af79cc507b90a224b6de4120876d1a36f#diff-948263b0172e85fc1a68026c2f7a1049

Here is a similar issue: https://github.com/KimiNewt/pyshark/issues/294

**Comment by 0x4D31** [comment]
No issues when using pyshark version 0.3.7.6 or older which shows the issue is because of that `-r` option added in version 0.3.7.8.

**Comment by mikewalshchicago** [comment]
Was there ever a resolution to this issue?  I am having the same problems you describe on the latest pyshark, and you're right that reverting to pyshark 0.3.7.6 takes care of the problem (partially).  If i let the capture run for a while on 0.3.7.6 with sniff_continuously(), it will eventually fail with a debug message like the following:

tshark: The file "/mnt/ramdisk/pyshark_00003_20190508113253.pcapng" doesn't exist.

surely this is because the file has rolled off (i'm using num_ring_files parameter because i really want sniff_continuously() to run forever).  I've tried to adjust both ring_file_size and num_ring_files, which i can use to make it go longer, but eventually it will fail.  I understand this is a different issue than what you reported, and i'll make a different issue about it, but becuse this is happening due to me being bound to 0.3.7.6 for now, i thought maybe you might have some insight.

udpshark = pyshark.LiveRingCapture(interface="em1", ring_file_size=4096, num_ring_files=50, ring_file_name="/mnt/ramdisk/pyshark.pcapng" )



on the current pyshark build I can't use LiveCapture or LiveRingCapture at all, because of the following:

tshark: You can't write both raw packet data and dissected packets to the standard output.

I changed all of my print statements to logging commands hoping that would work, but it doesnt

**Comment by poleguy** [comment]
Is this a duplicate/related: https://github.com/KimiNewt/pyshark/issues/477
