### ISSUE TITLE
Endianess issue in the Pyshark when parsing using XML

### ISSUE THREAD

**Issue by MohitKAgnihotri** [KimiNewt/pyshark#345]
I observe that when trying to get the hex_value of a layer attribute, the `show` and `raw_value` differ in the term of endianness. 

This is observed for a Zigbee capture where the destination address is `0xFFFC`. In the layer_field, the `show `presents it's value as `0xfffc `while the `raw_value `presents its value as `0xffcf`.

When a user tries to get the hex_value for the field, raw_value is used and hence incorrect value is returned to the user.

**Comment by MohitKumarAgniotri** [comment]
![image](https://user-images.githubusercontent.com/6726993/59262689-015a4700-8c40-11e9-9879-8e9d8a3a0d1f.png)

**Comment by MohitKumarAgniotri** [comment]
@KimiNewt Any insights would be helpful.

**Comment by kcexn** [comment]
If you look at the direct output of tshark. Do you see this as well?

**Comment by MohitKumarAgniotri** [comment]
No, when we look at the T-shark output, the value is correctly shown. I assume it uses the `show` value instead of `raw value`.

**Comment by antoine-girard-vallee** [comment]
I have observed a similar issue.
This is because ZigBee sends multi-byte entries LSB first⁰, unlike most network protocols. pyshark does not take this case into account when taking the raw byte value, but will display it correctly when taking the dissected "value" field. This makes the hex_value and int_value output flipped values.

Protocols with different byte orderings are a valid case; I believe this should be taken into account. Raw capture data cannot be used 'as is' because the interpretation depends on dissector knowledge. To work correctly, hex_value and int_value entries should be built from the "value" string.

@KimiNewt I am willing to make a patch for this, but I think it requires a discussion first as interpretation of the show field can cause issues.

Here is an example of a Zigbee pdml showing the issue:
`    
    <field name="zbee_nwk.src" showname="Source: 0xd52d" size="2" pos="13" show="0x0000d52d" value="2dd5"/>
    <field name="zbee_nwk.addr" showname="Address: 0xd52d" hide="yes" size="2" pos="13" show="0x0000d52d" value="2dd5"/>
    <field name="zbee_nwk.radius" showname="Radius: 29" size="1" pos="15" show="29" value="1d"/>
    <field name="zbee_nwk.seqno" showname="Sequence Number: 224" size="1" pos="16" show="224" value="e0"/>
    <field name="zbee_nwk.dst64" showname="Destination: 07:6e:30:58:00:12:4b:00 (07:6e:30:58:00:12:4b:00)" size="8" pos="17" show="07:6e:30:58:00:12:4b:00" value="004b120058306e07"/>
    <field name="zbee_nwk.addr64" showname="Extended Address: 07:6e:30:58:00:12:4b:00 (07:6e:30:58:00:12:4b:00)" hide="yes" size="8" pos="17" show="07:6e:30:58:00:12:4b:00" value="004b120058306e07"/>

`

0: Zigbee PRO 2015. you can find a pdf here: https://zigbeealliance.org/wp-content/uploads/2019/11/docs-05-3474-21-0csg-zigbee-specification.pdf
