### ISSUE TITLE
how to open a folder with many pcap files in one pyshark object?

### ISSUE THREAD

**Issue by ant1fr1z** [KimiNewt/pyshark#414]
how to open a folder with many pcap files in one pyshark object?

**Comment by jnich3ls0n** [comment]
This is probably a little late but I might be able to help answer this.

Pyshark is a Python wrapper for tshark. After reviewing the docs for tshark (https://www.wireshark.org/docs/man-pages/tshark.html) it doesn't look like there is a way to specify more than one input file.

Mergecap is a separate tool that can be used to merge multiple captures into one (https://www.wireshark.org/docs/man-pages/mergecap.html).

I don't see any Python wrapper projects for mergecap. In your program you could call mergecap as a subprocess to generate the file then use the Pyshark library to parse the merged pcap.

Since Pyshark is a tshark wrapper, I doubt mergecap functionality will be added to the project.
