### ISSUE TITLE
LiveCapture missing the latest packet when use_json and include_binary are True

### ISSUE THREAD

**Issue by matan1008** [KimiNewt/pyshark#429]
Hello,
I am trying to use the LiveCapture to capture packets in real time and get both their raw data and the parsed data. To do that, I did the following:

    import pyshark
    cap = pyshark.LiveCapture(interface="eth0", bpf_filter="udp port 7777", include_raw=True, use_json=True)
    for p in cap.sniff_continuously():
        print(p)

I noticed that sending a packet to udp port 7777 doesn't print anything, but when sending another packet, the first packet is being printed. After looking through the code, I noticed that `_extract_packet_json_from_data` in the `Capture` class is waiting to a packet separator, and if I understand correctly, it will be printed only when the next packet is received.

I would really like to contribute and submit a pull request that fixes it - I think about solving it by reading each character from the output and checking that `json.loads` doesn't throw any error, Will it be fine if I submit such a PR?

By the way, this package is really great!
Best regards,
Matan

**Comment by mfranzil** [comment]
Using Pyshark 0.5.2 built from source, looks that issue is still around. My code:

```
def monitor_pyshark(device):
    cap = pyshark.LiveRingCapture(
        interface=device,
        bpf_filter="udp",
        use_json=True,
        use_ek=True,
        include_raw=True,
        ring_file_size=1024 * 20,
        num_ring_files=3
    )

    try:
        cap.apply_on_packets(packet_callback_pyshark)
    except KeyboardInterrupt:
        exit(0)
```

Playing with the ring file parameters does not affect the output. When such a setting is used, the last packet of a network flow is systematically held in buffer until more packets arrive. 

This is a snippet of a QUIC monitoring application I'm developing. The first screenshot shows what a small flow outputs. The second screenshot shows the same output when using other sniffers (e.g. scapy) or once another network flow arrives with Pyshark. In the first screenshot, the APPLICATION_CLOSE frame is missing.

<img width="1440" alt="Screenshot 2022-08-07 at 19 05 36" src="https://user-images.githubusercontent.com/32071488/183302592-7eec0e17-7ed7-4794-b387-81438e1df6aa.png">

<img width="1440" alt="Screenshot 2022-08-07 at 19 06 01" src="https://user-images.githubusercontent.com/32071488/183302605-c294c877-9eef-482c-a609-73789e26a7c1.png">

I've debugged in every possible way, but obtained no relevant information about what is happening about that packet.
