### ISSUE TITLE
How to get packet.tcp.payload and packet.http.data as string?

### ISSUE THREAD

**Issue by AshishJha123** [KimiNewt/pyshark#458]
The return value for these attributes are in hex format seperated by ':'
Eg : 70:79:f6:2e: something like this.
When I am trying to decode it to plain string it doesn't work. What encoding is being used? I tried various different methods like codecs.decode(), binascii.unhexlify(), bytes.fromhex() also different encodings ASCII and UTF-8. Nothing worked, any help is appreciated. I am using python 3.6

`packet_payload= binascii.unhexlify(str(packet.tcp.payload).replace(":","")).decode("ASCII")`
`print(packet_payload)`

**Comment by hameddanesh** [comment]
i'm not sure this can be useful but i wrote this function for packet.tcp.payload and packet.udp.payload

def ByteArrayToString(byteArray):
    readableString = ""
    for byteCode in byteArray:
        readableString += chr(int(byteCode, 16))
    return readableString

print(ByteArrayToString("[payload goes here]"))
    
in some case it work's fine but in some case it prints weird strings which i think is due to encrypted data in payload or using some kind of flags to categorize payloads ( because apeariently payloads which begin with 17: don't get decoded well and they belong to ACK packets).
