### ISSUE TITLE
Can not parse 'X-Requested-With' from http header

### ISSUE THREAD

**Issue by Minzc** [KimiNewt/pyshark#51]
Hi, I am using pyshark to parse some pcap files. But it seems that pyshark is missing from information. If I use wireshark, I can see 'X-Request-With' in the http header. While I can not see it if I use pyshark to parse the same file.

**Comment by KimiNewt** [comment]
This seems to be caused by the fact that X-Requested-With does not, for some reason, have a field name.

It looks like this in the XML we get:
   <field name="" show="X-Requested-With: foo\r\n" size="23" pos="116" value="582d5265717565737465642d576974683a20666f6f0d0a"/>

Which I've only seen happen in "summary"-type fields. I'll try and see if we can somehow generalize this for HTTP headers and take the name from the show field, since HTTP headers are pretty important.

**Comment by Minzc** [comment]
Thanks for the response.

Perhaps you can try to add another field 'additional header' and put headers that can not be recognized into that field?

**Comment by KimiNewt** [comment]
This is accessible via `pkt.http.request_line.alternate_fields`

I have also added (just now in c1efec95a33260289c8627a1bbde6a9212aa8750) a method called get_field_by_showname, so it can be accessed in this way as well:

```python
p.http.get_field_by_showname('X-Requested-With').showname_value
```

It's a bit cumbersome but this is a rather rare occurrence. I have also added alternate fields to the repr/pretty print of the objects so you can more easily tell they're actually there.

**Comment by SentiDavidGuler** [comment]
Hey looks like there's an error when using the method `get_field_by_showname`. 

I'm using the 'pyshark-legacy' version due to old Python version we have (not my decision :( ). It seems the method tries to get the attribute 'showname_key' from a list:
```
def get_field_by_showname(self, showname):
        """
        Gets a field by its "showname"
        (the name that appears in Wireshark's detailed display i.e. in 'User-Agent: Mozilla...', 'User-Agent' is the
         showname)

         Returns None if not found.
        """
        for field in self._get_all_fields_with_alternates():
            if field.showname_key == showname:
                # Return it if "XXX: whatever == XXX"
                return field
```

When I run it I receive the following Exception:
```
In [179]: rep.http.get_field_by_showname("Pragma")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-179-4c8937c86616> in <module>()
----> 1 rep.http.get_field_by_showname("Pragma")

~/code/MalwareLab/.venv/lib/python3.4/site-packages/pyshark/packet/layer.py in get_field_by_showname(self, showname)
    187         """
    188         for field in self._get_all_fields_with_alternates():
--> 189             if field.showname_key == showname:
    190                 # Return it if "XXX: whatever == XXX"
    191                 return field

AttributeError: 'list' object has no attribute 'showname_key'
```
It looks like a very useful method but currently I can't use it, please help :(
