### ISSUE TITLE
How pyshark identifies the number of bits occupied by fields less than one byte？

### ISSUE THREAD

**Issue by ShadowLL** [KimiNewt/pyshark#545]
Similar to the DSCP field in the IP protocol header, how to identify the number of bits in this version field in the packet object parsed by pyshark's IMemCapture object?  I did not find any related methods or properties from the Layer object and the LayerField object.

**Comment by KimiNewt** [comment]
PyShark simply uses the wireshark parsing of the packet, so if this data exists in a field in Wireshark, it should be accessible.
You can attach a pcap and I can see if I can help out with it.

**Comment by ShadowLL** [comment]
For example, the Version and Header length fields of an IP packet header.
![IP报文头](https://user-images.githubusercontent.com/7976018/173041365-6fb8ccfd-3638-4b45-a70a-8c9213c3eb4d.png)
Another problem is how to determine whether a field with the same position is in a parallel relationship or a parent-child relationship, for example, Goose protocol packet as follows.
![goose报文](https://user-images.githubusercontent.com/7976018/173041661-4254a52c-963b-4005-9aac-a718fdab036f.png)

**Comment by ShadowLL** [comment]
> 

For example, the Version and Header length fields of an IP packet header.

![IP_header](https://user-images.githubusercontent.com/7976018/173042145-8e39d2c3-ae32-457b-94a8-0a6c9ad0a5ed.png)


Another problem is how to determine whether a field with the same position is in a parallel relationship or a parent-child relationship, for example, Goose protocol packet as follows.

![goose_protocol](https://user-images.githubusercontent.com/7976018/173042181-b73aa75e-e006-44e1-ace8-31dbe4d95af0.png)

**Comment by KimiNewt** [comment]
Still not entirely sure what you're asking. When it comes to the ip version you can access it by using `pkt.ip.version` and `pkt.ip.hdr_len`. Since these are just numbers you can convert them to binary yourself. You can also do `pkt.ip.version.showname` to get the full string that you see in Wireshark.

As for the other question, can you attach a pcap file? It's hard to know how extract it without seeing the actual packets. In general, you can access the field (same as the name listed on the bottom left of wireshark). If multiple exists you can access it via `pkt.layer.field.all_fields`
