### ISSUE TITLE
5G MIME multipart packets: First part is not decoded

### ISSUE THREAD

**Issue by llutze2s** [KimiNewt/pyshark#561]
Hey,

I discovered that the first part of MIME_multipart messages don´t get decoded.
The prettyprint of the message is decoded correctly:
![image](https://user-images.githubusercontent.com/32838560/176171836-3cfb00f7-db75-41c8-b69e-47eabba040df.png)

The output for 'print(packet['mime_multipart']._all_fields)' is incorrect. The first part is not decoded:
![image](https://user-images.githubusercontent.com/32838560/176173101-0e456310-91ab-44f9-8f7e-5dcfd4bbdb60.png)

As a workaround, you can use 'print(bytes.fromhex(packet['mime_multipart'].part).decode('utf-8'))' to decode the first part:
![image](https://user-images.githubusercontent.com/32838560/176173157-105c6436-0e7b-4534-8714-b7b797421aa2.png)

**Comment by llutze2s** [comment]
[oai-5gsa-rfsim.zip](https://github.com/KimiNewt/pyshark/files/9007819/oai-5gsa-rfsim.zip)

**Comment by KimiNewt** [comment]
It's a bit awkward because it's in a flat hierarchy, so for example if you want to get all the fields with the key `json_member` you can use `pkt.mime_multipart.json_member.all_fields`. 

You can also get the whole dict if you use the new EK mode in master. Might be more useful.
```
pcap = pyshark.FileCapture("/home/dorg/caps/oai-5gsa-rfsim.pcapng", use_ek=True)
pkt = pcap[209]
pkt.mime_multipart.json
```

So the data is there but just very awkward to retrieve. We should probably create a special way to fetch JSON-type objects. I'm closing this for now but you're welcome to create a feature request issue.
