### ISSUE TITLE
Saving packets to a pcap / pcap-ng file.

### ISSUE THREAD

**Issue by mattaereal** [KimiNewt/pyshark#81]
Is there a way to save a selection of packets to a file?
I can't find a way to do it. I was going to try to make a class based on LiveCapture that has the ability to save the list of self._packets into a file, but I got confused on the making and quit.

**Comment by KimiNewt** [comment]
You cannot save a selection of packets to a file because pyshark does not (currently) keep the raw packet data.
You can, however, use the "output_file" parameter in LiveCapture so that any packets that are captured will be written to a file. You can use this in conjunction with the filter parameters to save only certain packets to a file.
